### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [anhpnguyen/note-to-self#1]
This looks good, except it doesn't _quite_ meet one of the criteria:

> the model must have at least 3 attributes, of at least 3 separate data types

It looks like you have only attributes of type string and datetime. Can you add another attribute with a data type that is neither a `text` nor `datetime`? You can add a new attribute to an existing table by generating a migration like this:

```
rails generate migration AddAttributeNameToStories attribute_name:data_type
```

Then running `rake db:migrate`. You'll have to then update your controller and views with the new field.

One other issue is it looks like the date is always being displayed in UTC, when you probably want to use the time zone for Michigan. You can [learn how to change the time zone in Rails here](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html).

Let me know how that goes and if you have any questions!

**Comment by anhpnguyen** [comment]
Hi Chris! I have added one more attribute with data type : integer.
Originally I was going to have the attribute Subject of type string but I
must have enter text instead. For the time zone, I have something like
Time.zone = "Eastern Time (US & Canada)" and it replaced the UTC with
-0400. What do you suggest that I should do?

Thanks!

Anh Nguyen

**Comment by anhpnguyen** [comment]
One more thing, I was using : primary_key instead of :integer at first and
i got a nomethoderror. Let's say i used it and updated the views, would it
automatically generate an id for me when i create a new instant variable?

**Comment by chrisvfritz** [comment]
The -0400 is our current time zone, so that's actually what it should be - unless I'm misunderstanding the question. 

And great question about the primary key! Just like every table you create will automatically be given `created_at` and `updated_at` columns, each table will also be given an `id` column by default, which is populated with a unique ID every time a new record is created - so you actually don't need to manually create a primary key.

**Comment by anhpnguyen** [comment]
Thanks Chris! I have made all the necessary changes. However my css doesn't
seem to apply, and I tried using both css and sass. Can you help me out?
Also where would be a good place to learn css and sass?

**Comment by chrisvfritz** [comment]
:+1: Looks good. I'm not seeing a problem with the way styles are appearing though. Can you point me to an example of something you expect to work, but doesn't seem to be?

As for learning CSS, I recommend checking out [Treehouse's CSS Foundations course](http://teamtreehouse.com/library/css-foundations). It's not free, but it's a heck of a lot cheaper than a university course, and I've heard from many people that it was extremely helpful in making them much more comfortable with CSS in a short amount of time. 

Once you master that, [the free SCSS guide](http://sass-lang.com/guide) should help you learn about the little extra things that SCSS allows you to do on top of regular CSS.
